DEFINE_TEST(stack_array, "stack arrays")
DEFINE_TEST(atomic, "C11 atomic types")
DEFINE_TEST(badcall, "calling non-functions")
DEFINE_TEST(capret, "return addresses")
DEFINE_TEST(fnptr, "function pointers")
DEFINE_TEST(init, "global initialisation")
DEFINE_TEST(intptr, "intptr_t support")
DEFINE_TEST(null, "null pointer support")
DEFINE_TEST(smallint, "integer and pointer aliasing")
DEFINE_TEST(unions, "unions of capabilities and data")
